program: model_sweep.py
name: unet-image-segmentation-sweep
method: bayes
metric:
  goal: maximize
  name: test_iou
parameters:
  learning_rate:
    min: 0.000001
    max: 0.0001
  batch_size:
    values: [32]
  max_epochs:
    values: [100]
  out_channels:
    values: [16, 32, 64, 128]
  scheduler_step:
    values: [10]
  scheduler_gamma:
    values: [0.1, 0.3, 0.5]
  encoder_dropout: 
    max: 0.4
    min: 0.0